version: '3'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  web-app:
    build: .
    container_name: web-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
    depends_on:
      - mysql-db
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-data:

